config/routes.rb
CurriculumMgmt::Application.routes.draw do
  get "landing_page/index"
  root "landing_page#index"
  devise_for :users, :path => 'accounts' 
  resources :justifications do
    resources :answers
  end
  resources :users do
    get :manage_years
    get :choose_catalog
    patch :update_catalog
    resources :student_programs, shallow: true do
      patch :update_program
      resources :validations
      resources :justifications do
        resources :answers
        resources :constraint_exceptions
      end
      get :status
      get :configure
      get :new_validation
      get :check
      resources :years, shallow: true do
        get :pass
        get :fail
        resources :semesters, shallow: true do
          resources :courses
        end
      end
    end
  end
  resources :validations do
    get :validate
  end
  

  resources :catalogs, shallow: true do
    get :upgrade
    patch :upload
    resources :courses
    resources :p_modules, shallow: true do
      resources :p_modules
      resources :courses, shallow: true do
        resources :constraints
      end
    end
    resources :programs, shallow: true do
      resources :properties
      resources :courses
      resources :p_modules
    end
  end
end
  

app/models/program.rb
require 'constraints_checker/constraints/property_constraint'

class Program < ActiveRecord::Base
	has_many :properties, as: :entity, dependent: :destroy
	belongs_to :catalog
	has_many :student_programs, dependent: :destroy
	has_and_belongs_to_many :p_modules
	has_and_belongs_to_many :courses
	accepts_nested_attributes_for :properties
	validates_associated :properties


	def self.find_by_property(property_type, property_value, catalog)
		catalog.programs.includes(:properties).where('property.p_type' => property_type, 'property.p_value' => property_value).first
	end

	def self.page_name
		"PROGRAMMES"
	end

	def complete_name
		self.catalog.name + " : " + self.catalog.academic_year.name + " - " + self.name
	end

	def credits
		get_property("CREDITS")
	end


	def mandatory_modules
		modules = []
		self.p_modules.without_parent.each do |m|
			modules << m if m.mandatory?
		end
		return modules
	end

	def self.header
		return ["NAME", "MIN", "MAX", "CREDITS"]
	end

	def count_credits
		p self.name
		result = 0
		self.courses.each do |course|
			result += course.credits.to_i
		end
		self.p_modules.each do |p_module|
			result += p_module.count_credits.to_i
		end
		return result
	end



	def optional_modules
		modules = []
		self.p_modules.without_parent.each do |m|
			modules << m unless m.mandatory?
		end
		return modules
	end

	# return courses (with semester property == 1) that belong to the program, his modules or his modules sub_modules 
	def first_semester_courses
		result = self.courses.first_semester
		self.p_modules.includes(:sub_modules).each do |pm|
			result += pm.courses.first_semester
			pm.sub_modules.each do |sm|
				result +=  sm.courses.first_semester
			end
		end
		return result
	end
	# ... (with semester property ==2) ...
	def second_semester_courses
		result = self.courses.second_semester
		self.p_modules.includes(:sub_modules).each do |pm|
			result +=  pm.courses.second_semester
			pm.sub_modules.each do |sm|
				result +=  sm.courses.second_semester
			end
		end
		return result
	end


	# ... ... ... (with mandatory property == false)

	def first_semester_optional_courses
		result = prgrm.courses.first_semester.optional
		self.p_modules.each do |pm|
			result = result +  pm.courses.first_semester.optional
			pm.sub_modules.each do |sm|
				result = result +  sm.courses.first_semester.optional
			end
		end
		return result
	end

	# ... ... ... (with mandatory property == true)

	def second_semester_optional_courses
		result = self.courses.second_semester.mandatory
		self.p_modules.each do |pm|
			result = result +  pm.courses.second_semester.optional
			pm.sub_modules.each do |sm|
				result = result +  sm.courses.second_semester.optional
			end
		end
		return result
	end

	def mandatory_courses
		result = self.courses.mandatory
		self.p_modules.each do |pm|
			result += pm.courses.mandatory
			pm.sub_modules.each do |sm|
				result +=  sm.courses.mandatory
			end
		end
		return result
	end

	def all_courses
		result = self.courses
		self.p_modules.each do |pm|
			result += pm.all_courses
		end

		return result

	end

	def update_properties(properties)
		properties.each do |key, value|
			p = self.properties.where(:p_type => key.to_s).first
			
			if p.nil?
				self.properties.create(:p_type => key.to_s, :value => value.to_s)
			
			else
				p.value = value.to_s
				p.save
			end
		end
	end

	def name
		name = 	get_property("NAME")
		if name.eql? ""
			name = "NONE"
		end
		return name
	end

	def min
		result = get_property("MIN")
		if result.eql? "NONE"
			result = 0
		end
		return result.to_i
	end

	def max
		result = get_property("MAX")
		if result.eql? "NONE"
			result = 999
		end
		return result.to_i
	end

	def has_modules?
		self.p_modules.count > 0
	end

	def has_courses?
		self.courses.count > 0
	end

	def self.find_by_property(property_type, property_value, catalog)
		catalog.programs.includes(:properties).where('properties.p_type' => property_type, 'properties.value' => property_value).first
	end

	def as_json(option={})
		if self.has_modules? and self.has_courses?
			{
				:name => self.properties.main.value,
				:children => self.p_modules.as_json,
				:children => self.courses.as_json			
			}
		elsif self.has_modules? and ! self.has_courses?
			{
				:name => self.properties.main.value,
				:children => self.p_modules.as_json
			}
		elsif !self.has_modules? and self.has_courses?
			{
				:name => self.properties.main.value,
				:children => self.courses.as_json
			}
		end
			
	end

	def self.constraints_header
		["NAME", "MIN", "MAX"]
	end
 	
 	def properties_to_hash
    props = Hash.new
    props["NAME"] = self.name
    self.properties.each do |p|
      props[p.p_type.to_s] = p.value.to_s unless p.p_type.eql? "NAME"
    end
    props
  end
private
	def get_property(property_type)
    p = self.properties.where(p_type: property_type).first
    if p.nil? 
      return "NONE"
    else
      return p.value
    end
  end 
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @catalog = Catalog.find(params[:catalog_id])
    @programs = @catalog.programs.includes(:courses, p_modules: [:courses, {sub_modules: :courses}])
  end


  def destroy
    @program = Program.find(params[:id])
    @catalog = @program.catalog
    @program.destroy
    redirect_to catalog_programs_path(@catalog)
  end

  def new
    @catalog = Catalog.find(params[:catalog_id])
    @p_modules = @catalog.p_modules.without_parent
    @program = Program.new
    2.times do
      property = @program.properties.build
    end
    @properties_type = ["credits", "name"]
  end
  
  def create
    @properties_type = ["credits", "name"]
    @catalog = Catalog.find(params[:catalog_id])
    @program = @catalog.programs.create(program_params)
    if @program.errors.any? 
      render action: :new
    else
      params[:program][:p_modules][:ids].each do |value|
        @program.p_modules << PModule.find(value.to_i) unless value.eql? "0"
      end
      params[:program][:courses][:ids].each do |value|
        @program.courses << Course.find(value.to_i) unless value.eql? "0"
      end
      redirect_to @program
    end
  end

  def show
    @program = Program.find(params[:id])
    @catalog = @program.catalog
  end

private

  def program_params
    params.require(:program).permit(properties_attributes: [:p_type, :value])
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_admin_index.html.haml
-i = 0
- programs.each do |p|
  .panel.panel-default
    .panel-heading
      %a{"data-parent" => "#"+id, "data-toggle" => "collapse", :href => "#"+id+"program_"+i.to_s}
        = p.name
        .pull-right
          = link_to p, method: :delete, data:{confirm: 'Are you sure?'} do
            %span.glyphicon.glyphicon-remove{style: 'color: red;'}
          = link_to p do
            %span.glyphicon.glyphicon-zoom-in
    .panel-collapse.collapse{id: id+"program_"+i.to_s}
      - if p.p_modules.count > 0
        .panel.panel-default
          .panel-heading
            %a{"data-parent" => "#"+id+"program_"+i.to_s, "data-toggle" => "collapse", :href => "#"+id+"program_"+i.to_s+"_modules"}
              Modules
              %span.badge.pull-right
                = p.p_modules.count
          .panel-collapse.collapse{id: id+"program_"+i.to_s+"_modules"}
            = render 'p_modules/admin_index', p_modules: p.p_modules, id: id+"program_"+i.to_s+"_modules"
      - if p.courses.count > 0
        .panel.panel-default
          .panel-heading
            %a{"data-parent" => "#"+id+"program_"+i.to_s, "data-toggle" => "collapse", :href => "#"+id+"program_"+i.to_s+"_courses"}
              Cours
              %span.badge.pull-right
                = p.courses.count
          .panel-collapse.collapse{id: id+"program_"+i.to_s+"_courses"}
            = render 'courses/admin_index', courses: p.courses, id: id+"program_"+i.to_s+"_courses"


  - i += 1



= link_to 'Nouveau Programme', new_catalog_program_path(catalog), class: "btn btn-primary btn-lg btn-block"

app/views/programs/_error_messages.html.haml
- if object.errors.any?
  .text-center
    %h4 Votre programme n'a pas été créé
    - object.errors.full_messages.each do |msg|
      .alert.alert-danger.alert-dismissable
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
        = msg

app/views/programs/_index.html.haml
-i = 0
.panel.panel-default
  .panel-heading.text-center
    Programmes disponnibles
  .panel-body
    .alert.alert-info.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      Pour avoir accès à d'anciens programmes, cliquez
      = link_to "ici", user_choose_catalog_path(current_user)
      pour changer de catalogue
    - programs.each do |p|
      .panel.panel-default
        .panel.panel-heading
          %a{"data-parent" => "main", "data-toggle" => "collapse", :href => "#program_"+i.to_s}
            = p.name
            .pull-right
              = link_to p do
                %span.glyphicon.glyphicon-zoom-in
        .panel-collapse.collapse{id: "program_"+i.to_s}
          - if p.p_modules.count  > 0
            .panel.panel-default
              .panel.panel-heading
                %a{"data-parent" => "main", "data-toggle" => "collapse", :href => "#program_"+i.to_s+"_modules"}
                  Modules
                  %span.badge.pull-right
                    = p.p_modules.count
              .panel-collapse.collapse{id: "program_"+i.to_s+"_modules"}
                = render 'p_modules/index', p_modules: p.p_modules, id: "program_"+i.to_s+"_modules"
          - if p.courses.count > 0
            .panel.panel-default
              .panel.panel-heading
                %a{"data-parent" => "main", "data-toggle" => "collapse", :href => "#program_"+i.to_s+"_courses"}
                  Cours
                  %span.badge.pull-right
                    = p.courses.count
              .panel-collapse.collapse{id: "program_"+i.to_s+"_courses"}
                = render 'courses/index', courses: p.courses, id: "program_"+i.to_s+"_courses"
      - i += 1

app/views/programs/_property_field.html.haml
= f.hidden_field :p_type, value: type
.col-md-2
  = f.label :p_type,  type.upcase, class: 'control-label'
.col-md-4
  = f.text_field :value, class: 'form-control'

app/views/programs/index.html.haml
.col-md-8.col-md-offset-2
	- if current_user.admin?
		= render 'admin_index', programs: @programs, catalog: @catalog
	- else
		= render "index", programs: @programs, catalog: @catalog

app/views/programs/new.html.haml
.col-md-8.col-md-offset-2
  .panel.panel-default
    .panel-heading.text-center
      %h4 Nouveau Programme
    .panel-body
      .form-horizontal
        = form_for [@catalog, @program] do |f|
          = render 'error_messages', object: f.object
          .form-group
            = f.fields_for :properties do |builder|
              = render 'property_field', f: builder, type: @properties_type.pop
          %ul.nav.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#modules"} MODULES
            %li.pull-right
              %a{"data-toggle" => "tab", :href => "#courses"} COURS
          .tab-content
            #modules.tab-pane.active
              = f.fields_for :p_modules do |builder|
                = render 'programs/p_module/p_modules', f: builder, p_modules: @catalog.p_modules.without_parent
            #courses.tab-pane
              = f.fields_for :courses do |builder|
                = render 'programs/course/courses', f: builder, courses: @catalog.courses.without_parent
          %p
            = f.submit "Créer le programme", class:"btn btn-primary btn-lg btn-block"



          

app/views/programs/show.html.haml
.col-md-8.col-md-offset-2
  .panel.panel-default
    .panel-heading
      .text-center
        = @program.name
    .panel-heading.text-center
      = link_to :back do
        %span.glyphicon.glyphicon-chevron-left
          Retour vers la page précédente
    .panel-body
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th.text-center NOM
            %th.text-center Crédits MIN
            %th.text-center Crédits MAX
        %tbody
          %tr
            %td.text-center
              = @program.name
            %td.text-center
              = @program.min
            %td.text-center
              = @program.max