config/routes.rb
CurriculumMgmt::Application.routes.draw do
  get "landing_page/index"
  root "landing_page#index"
  devise_for :users, :path => 'accounts' 
  resources :justifications do
    resources :answers
  end
  resources :users do
    get :manage_years
    get :choose_catalog
    patch :update_catalog
    resources :student_programs, shallow: true do
      patch :update_program
      resources :validations
      resources :justifications do
        resources :answers
        resources :constraint_exceptions
      end
      get :status
      get :configure
      get :new_validation
      get :check
      resources :years, shallow: true do
        get :pass
        get :fail
        resources :semesters, shallow: true do
          resources :courses
        end
      end
    end
  end
  resources :validations do
    get :validate
  end
  

  resources :catalogs, shallow: true do
    get :upgrade
    patch :upload
    resources :courses
    resources :p_modules, shallow: true do
      resources :p_modules
      resources :courses, shallow: true do
        resources :constraints
      end
    end
    resources :programs, shallow: true do
      resources :properties
      resources :courses
      resources :p_modules
    end
  end
end
  

app/models/year.rb
class Year < ActiveRecord::Base
  belongs_to :student_program
  belongs_to :academic_year
  has_one :first_semester, dependent: :destroy
  has_one :second_semester, dependent: :destroy

  
  scope :passed, -> {where("status = ?", 2)}
  scope :failed, -> {where("status = ?", 1)}
  scope :current, -> {where("status = ?", 0)}

  def passed?
    self.status.eql? 2
  end

  def course_present?(course)
    result = self.first_semester.course_present?(course)
    return result unless ! result
    result = self.second_semester.course_present?(course)
    return result
  end

  def migrate(catalog)
    p "migrating year ..."
    missing_courses = []
    missing_courses += self.first_semester.migrate(catalog)
    missing_courses += self.second_semester.migrate(catalog)
    return missing_courses
  end

  def failed?
    self.status.eql? 1
  end

  def pass
    self.status = 2
    self.save 
  end

  def status_name
    if self.status.eql? 2
      return 'Réussie'
    elsif self.status.eql? 1
      return 'Ratée'
    else
      return 'En cours'
    end
  end 

  def fail
    self.status = 1
    self.save
  end

  def count_credits
    result = 0
    result += first_semester.count_credits
    result += second_semester.count_credits
    return result
  end


  #look for old version of course when checking years that belongs to older programs
  #first case : catalog is the same
  #second case : A catalog migration occurs; we have to check for an older catalog
  def get_old_course_objects(catalog)
    courses = []
    if ! catalog.id.eql? self.student_program.program.catalog
      new_program = catalog.find_program(self.student_program.program.name).first
      courses += self.first_semester.get_old_course_objects_for_migrated_program(new_program, self.academic_year.start_year, self.academic_year.end_year) unless self.first_semester.nil?
      courses += self.second_semester.get_old_course_objects_for_migrated_program(new_program, self.academic_year.start_year, self.academic_year.end_year) unless self.second_semester.nil?
    else
      courses += self.first_semester.get_old_course_objects(self.academic_year.start_year, self.academic_year.end_year) unless  self.first_semester.nil?
      courses += self.second_semester.get_old_course_objects(self.academic_year.start_year, self.academic_year.end_year) unless  self.second_semester.nil?
    end
    return courses
  end

  def get_course_objects
    courses = []
    if self.status.eql? "0"
      courses += self.first_semester.get_courses_objects(self.academic_year.start_year, self.academic_year.end_year) unless  self.first_semester.nil?
      courses += self.second_semester.get_courses_objects(self.academic_year.start_year, self.academic_year.end_year) unless self.second_semester.nil?
    else
      courses += self.first_semester.get_courses_objects_for_migrated_program(self.student_program.program, self.academic_year.start_year, self.academic_year.end_year) unless self.first_semester.nil?
      courses += self.second_semester.get_courses_objects_for_migrated_program(self.student_program.program, self.academic_year.start_year, self.academic_year.end_year) unless self.second_semester.nil?
    end
    return courses
  end

end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource


  def new
    @student_program = StudentProgram.find(params[:student_program_id])
    @year = Year.new
    @year.build_first_semester
    @year.build_second_semester
  end

  def create
    @student_program = StudentProgram.find(params[:student_program_id])
    @year = @student_program.years.create(year_params)
    @first_semester = @year.create_first_semester
    @second_semester = @year.create_second_semester
    params[:first_semester][:ids].each do |id|
      @first_semester.courses << Course.find(id.to_i) unless id.eql? "0"
    end unless params[:first_semester].nil?

    params[:second_semester][:ids].each do |id|
      @second_semester.courses << Course.find(id.to_i) unless id.eql? "0"
    end unless params[:second_semester].nil?
    
    @student_program.uncheck
    @student_program.devalidate
    redirect_to @year.student_program
  end

  def pass
    @year = Year.find(params[:year_id])
    @year.pass
    redirect_to user_manage_years_path(current_user)
  end

  def edit
    @year = Year.includes(:first_semester, :second_semester).find(params[:id])
  end

  def update
    @year = Year.includes(:first_semester, :second_semester).find(params[:id])
    @year.first_semester.courses = []
    @year.second_semester.courses = []
    params[:first_semester][:ids].each do |id|
      @year.first_semester.courses << Course.includes(:properties).find(id.to_i) unless id.eql? "0"
    end unless params[:first_semester].nil?

    params[:second_semester][:ids].each do |id|
      @year.second_semester.courses << Course.includes(:properties).find(id.to_i) unless id.eql? "0"
    end unless params[:second_semester].nil?

    if current_user.admin?
      @year.fail
      redirect_to user_manage_years_path(current_user)
    else
      @year.update(year_params)
      @year.student_program.devalidate
      @year.student_program.uncheck
      redirect_to @year.student_program
    end
  end

  def fail
    @year = Year.find(params[:year_id])
    @year.fail
  end

  def destroy
    @year = Year.find(params[:id])
    @student_program = @year.student_program
    @year.destroy
    redirect_to student_program_student_program_configure_path(@student_program)
  end

  def show
    @year = Year.includes(:first_semester, :second_semester).find(params[:id])
    @student_program = @year.student_program
  end

  def index
    @student_program = StudentProgram.find(params[:student_program_id])
    @years = @student_program.years
  end

private

  def year_params
    params.require(:year).permit(:academic_year_id)
  end
    
  def record_history
    session[:history] ||= []
    session[:history].push request.url
    session[:history] = session[:history].last(10)
  end

  def back
    session[:history].pop unless session.nil?
    root_path if session.nil?
  end

end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_admin_edit.html.haml
.panel.panel-default
  .panel-heading.text-center
    Cocher les cours crédités
  .panel-body
    .form-horizontal
      = form_for year do |f|
        .form-group
          = fields_for :first_semester do |builder|
            - year.first_semester.courses.each do |course|
              = render 'years/new/course', f: builder, course: course, checked: true
          = fields_for :second_semester do |builder|
            - year.second_semester.courses.each do |course|
              = render 'years/new/course', f: builder, course: course, checked: true

        = f.submit "Marquer l'année comme ratée", class: "btn btn-primary btn-lg btn-block"

app/views/years/_edit.html.haml
.panel.panel-default
  .panel-heading.text-center
    Modifier l'année
  .panel-body
    .form-horizontal
      = form_for year do |f|
        .form-group
          .col-md-3
            = f.label :année, class: 'control-label'
          .col-md-9
            = collection_select(:year, :academic_year_id, AcademicYear.all, :id, :name, {}, {:class => 'form-control'})
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", :href => "#first_semester"} Premier Quadri
          %li.pull-right
            %a{"data-toggle" => "tab", :href => "#second_semester"} Second Quadri
        .tab-content
          #first_semester.tab-pane.active
            = fields_for :first_semester do |builder|
              = render 'years/edit/courses', semester: year.first_semester, id: "first", f: builder

          #second_semester.tab-pane
            = fields_for :second_semester do |builder|
              = render 'years/edit/courses', semester: year.second_semester, id: "second", f: builder
        = f.submit "Modifier l'année", class: "btn btn-primary btn-lg btn-block"

app/views/years/edit.html.haml
.col-md-8.col-md-offset-2
  - if current_user.admin?
    = render "admin_edit", year: @year
  - else
    = render "edit", year: @year

app/views/years/index.html.haml
.col-md-8.col-md-offset-2
  %h3.text-center
    Années du programme de cours
  .panel.panel-default
    .panel-heading.text-center
      = link_to @student_program do
        %span.glyphicon.glyphicon-chevron-left
          Retour vers la page précédente
    .panel-body
      - @years.each do |c|
        .btn-group.btn-group-justified 
          = link_to years.academic_year.name+" - Plus d'infos", c, class: "btn btn-primary btn-block"
          = link_to "Supprimer", c, method: :delete, data: {confirm: 'Êtes vous sûr?'}, class: "btn btn-danger btn-block", disabled: (c.passed? or c.failed?)

      = link_to 'Ajouter une nouvelle année', new_student_program_year_path(@student_program), class: "btn btn-default btn-block"

app/views/years/new.html.haml
.col-md-8.col-md-offset-2
  .panel.panel-default
    .panel-heading.text-center
      %h4 Nouvelle Année
    .panel-body
      .form-horizontal
        = form_for [@student_program, @year] do |f|
          .form-group
            .col-md-3
              = f.label :année, class: 'control-label'
            .col-md-9
              = collection_select(:year, :academic_year_id, AcademicYear.all, :id, :name, {}, {:class => 'form-control'})
          %ul.nav.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#first_semester"} Premier Quadri
            %li.pull-right
              %a{"data-toggle" => "tab", :href => "#second_semester"} Second Quadri
          .tab-content
            #first_semester.tab-pane.active
              = fields_for :first_semester do |builder|
                = render 'years/new/courses', courses: @student_program.first_semester_available_courses, id: "first", f: builder
            #second_semester.tab-pane
              = fields_for :second_semester do |builder|
                = render 'years/new/courses', courses: @student_program.second_semester_available_courses, id: "second", f: builder
          = f.submit "Ajouter l'année", class: "btn btn-primary btn-lg btn-block"

app/views/years/show.html.haml
.col-md-8.col-md-offset-2
  %h2.text-center 
    Année -
    = @year.academic_year.name
  .panel.panel-default
    .panel-heading.text-center
      = link_to student_program_student_program_configure_path(@student_program) do
        %span.glyphicon.glyphicon-chevron-left
          Retour vers la configuration de votre programme
    .panel-body
      %ul.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#first_semester"} Premier Quadri
        %li
          %a{"data-toggle" => "tab", :href => "#second_semester"} Second Quadri
      .tab-content
        #first_semester.tab-pane.active
          .panel.panel-default
            .panel-heading.text-center
              Cours
            .panel-body
              = render 'years/show/courses', courses: @year.first_semester.courses
        #second_semester.tab-pane
          .panel.panel-default
            .panel-heading.text-center
              Cours
            .panel-body
              = render 'years/show/courses', courses: @year.second_semester.courses    