config/routes.rb
CurriculumMgmt::Application.routes.draw do
  get "landing_page/index"
  root "landing_page#index"
  devise_for :users, :path => 'accounts' 
  resources :justifications do
    resources :answers
  end
  resources :users do
    get :manage_years
    get :choose_catalog
    patch :update_catalog
    resources :student_programs, shallow: true do
      patch :update_program
      resources :validations
      resources :justifications do
        resources :answers
        resources :constraint_exceptions
      end
      get :status
      get :configure
      get :new_validation
      get :check
      resources :years, shallow: true do
        get :pass
        get :fail
        resources :semesters, shallow: true do
          resources :courses
        end
      end
    end
  end
  resources :validations do
    get :validate
  end
  

  resources :catalogs, shallow: true do
    get :upgrade
    patch :upload
    resources :courses
    resources :p_modules, shallow: true do
      resources :p_modules
      resources :courses, shallow: true do
        resources :constraints
      end
    end
    resources :programs, shallow: true do
      resources :properties
      resources :courses
      resources :p_modules
    end
  end
end
  

app/models/justification.rb
class Justification < ActiveRecord::Base
  belongs_to :student_program
  has_many :answers, dependent: :destroy
  has_many :constraint_exceptions, dependent: :destroy

  scope :unread, -> {where("read = ?", false)}
  scope :read, -> {where("read = ?", true)}
  accepts_nested_attributes_for :constraint_exceptions


  def has_uncompleted_exceptions?
    self.constraint_exceptions.un_completed.count > 0
  end

  def check_and_mark_constraint_exceptions
    self.constraint_exceptions.each do |ce|
      if ! (ce.message.nil? or ce.message.eql? "")
        ce.complete
      end
    end
  end

  # tag justification and all the answer he get to read when user responds. 
  def tag_as_read(user)
    self.read = true
    self.save
    self.answers.each do |a|
      a.read = true unless a.user_id.eql? user.id #we don't to tag as read his answers
      a.save
    end
  end

  
end

app/controllers/justifications_controller.rb
class JustificationsController < ApplicationController
  helper JustificationsHelper
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def new
    @student_program = StudentProgram.find(params[:student_program_id])
    @justification = @student_program.build_justification
  end

  def create
    @student_program = StudentProgram.find(params[:student_program_id])
    @justification = @student_program.create_justification(justification_params)
    if @justification.errors.any?
      render action: :new
    else
      @student_program.check
      redirect_to @student_program
    end
  end

  def show
    @justification = Justification.includes(answers: :user, constraint_exceptions: :entity, student_program: [:user, p_modules: [:courses, :sub_modules], years: [:first_semester, :second_semester]]).find(params[:id])
    @answer = Answer.new
  end

  def index
    @justifications = Justification.includes(answers: :user, constraint_exceptions: :entity, student_program: [:user, p_modules: [:courses, :sub_modules], years: [:first_semester, :second_semester], program: [ :courses, p_modules: [:courses, :sub_modules]]]).all
    @answer = Answer.new
  end

  def update
    @justification = Justification.find(params[:id])
    @justification.update(justification_params)
    @justification.update(read: false)
    @justification.check_and_mark_constraint_exceptions
    if @justification.errors.any?
      @student_program = @justification.student_program
      rerdirect_to @justification.student_program
    else
      @justification.student_program.check
      redirect_to @justification.student_program
    end
  end

  def edit
    @justification = Justification.find(params[:id])
    @student_program = @justification.student_program

  end

private

  def justification_params
    params.require(:justification).permit(:student_program_id, :content, constraint_exceptions_attributes: [:id, :message])
  end
end

app/helpers/justifications_helper.rb
module JustificationsHelper
  def render_constraint(exception, student_program, i)
    case exception.constraint_type
    when "Prerequisite"
      render partial: 'prerequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "Corequisite"
      render partial:'corequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "Mandatory"
      render partial:'mandatory', locals: {exception: exception, student_program: student_program, i:i}
    when "OrCorequisite"
      render partial:'or_corequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "OrPrerequisite"
      render partial:'or_prerequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "XorCorequisite"
      render partial:'xor_corequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "XorPrerequisite"
      render partial:'xor_prerequisite', locals: {exception: exception, student_program: student_program, i:i}
    when "Min"
      render partial:'min', locals: {exception: exception, student_program: student_program, i:i}
    when "Max"
      render partial:'max', locals: {exception: exception, student_program: student_program, i:i}
    end
  end
end

app/views/justifications/_answers.html.haml
%ul.list-group
  - answers.each do |a|
    %li.list-group-item
      = simple_format(a.content)
      .small.pull-right
        envoyé par
        = a.user.email
      %br

app/views/justifications/_constraint_exceptions.html.haml
- i = 1
- constraint_exceptions.each do |exception|
  = render_constraint(exception, student_program, i)
  - i += 1

app/views/justifications/_corequisite.html.haml
%tr
  %td.text-center
    = i
  %td
    Le corequis
    = exception.entity.courses.first.name 
    du cours
    = exception.entity.course.name
    n'est pas présent
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_courses.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th.text-center
        Cours concernés
      %th.text-center
        Présent?
  %tbody
    - courses.each do |course|
      %tr
        %td.text-center
          = course.name
        %td.text-center
          - present = student_program.course_present?(course)
          - if present
            %span.label.label-success
              OUI
          - else
            %span.label.label-danger
              NON

app/views/justifications/_justification.html.haml
.panel.panel-default
  .panel-heading
    .text-center
      - if current_user.admin?
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#"+id.to_s}
          = justification.student_program.user.email
      - else
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#"+id.to_s}
          Messages
  .panel-collapse.collapse{:id => id}
    .panel-body
      / %p
      /   = simple_format(justification.content)
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th.text-center #
            %th.text-center Description
            %th.text-center Justification
        %tbody
          = render "constraint_exceptions", constraint_exceptions: justification.constraint_exceptions, student_program: justification.student_program
      = render 'answers', answers: justification.answers
      = render 'new_answer', justification: justification, answer: answer

app/views/justifications/_mandatory.html.haml
%tr
  %td.text-center
    = i
  %td
    - if exception.entity.class.name.eql? "Course"
      %strong
        Le cours obligatoire
        = exception.entity.name
        n'est pas présent dans votre programme
        %br/
    - else
      %strong
        Les cours obligatoires du module
        = exception.entity.name
        ne sont pas présents
        %br/
      = render 'courses', courses: exception.entity.courses, type: "Cours obligatoires", student_program: student_program
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_max.html.haml
%tr
  %td.text-center
    = i
  %td
    Le maximum requis
    %span.badge 
      = exception.entity.max
    pour le
    - if exception.entity.class.name.eql? "Program"
      Programme
    - else
      Module
    %span.badge  
      = exception.entity.name
    
    est dépassé. Crédits actuels:
    
    - if exception.entity.class.name.eql? "Program"
      %span.badge
        = student_program.count_credits
    - else
      %span.badge
        = student_program.count_credits_for_module(exception.entity) 
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_min.html.haml
%tr
  %td.text-center
    = i
  %td
    Le minimum requis
    %span.badge 
      = exception.entity.min
    pour le
    - if exception.entity.class.name.eql? "Program"
      Programme
    - else
      Module
    %span.badge  
      = exception.entity.name
    
    n'est pas atteint. Crédits actuels:
    
    - if exception.entity.class.name.eql? "Program"
      %span.badge
        = student_program.count_credits
    - else
      %span.badge
        = student_program.count_credits_for_module(exception.entity) 
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_or_corequisite.html.haml
%tr
  %td.text-center
    = i
  %td
    %strong
      Le corequis (OR)
      = exception.entity.course.name
      n'est pas valide
      %br/
    = render 'courses', courses: exception.entity.courses, type: "Corequis disjonctif (OR)", student_program: student_program
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_prerequisite.html.haml
%tr
  %td.text-center
    = i
  %td
    Le prérequis
    = exception.entity.courses.first.name 
    du cours
    = exception.entity.course.name
    n'est pas présent
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/_xor_prerequisite.html.haml
%tr
  %td.text-center
    = i
  %td
    %strong
      Le prérequis (XOR) du cours
      = exception.entity.course.name
      n'est pas valide
      %br/
    = render 'courses', courses: exception.entity.courses, type: "Prérequis disjonctif exclusif(XOR)", student_program: student_program
  %td.text-center
    - if exception.message.nil? or exception.message.eql? ""
      %span.label.label-danger
        AUCUNE
    - else
      = simple_format(exception.message)

app/views/justifications/edit.html.haml
.col-md-8.col-md-offset-2
  .panel.panel-default
    .panel-heading.text-center
      Justifier les contraintes 
      = link_to "non respectées", student_program_student_program_check_path(@student_program)
      du programme
    .panel-body
      .form
        = form_for @justification do |f|
          = render 'error_messages', object: f.object
          .form-group
            .text-center
              = f.label :justification
            = f.text_area :content, class: 'form-control'
          = f.submit "Ajouter la justification", class: "btn btn-primary btn-lg btn-block"

app/views/justifications/index.html.haml
.panel.panel-default
  .panel-heading.text-center
    Discussions
  .panel-body
    - @justifications.each do |justification|
      = render 'justification', justification: justification, id: justification.id, answer: @answer

app/views/justifications/show.html.haml
.panel.panel-default
  .panel-heading.text-center
    Discussion
  .panel-body
    = render 'justification', justification: @justification, id: @justification.id, answer: @answer